Selfie: Implement QR scanner
SebaUbuntu/android_packages_apps_Selfie pull request #32
Opened 2022-08-09 21:46 UTC by luk1337

Change-Id: Ie6011ed5e5782c8244777f3026e8a6f308820113

2022-08-09 22:04 UTC, luk1337 commented
![ADB Screenshot from 2022-08-10 00-03-34](https://user-images.githubusercontent.com/6830979/183769814-5dabcc7c-a13f-4226-b222-675c1265ac51.png)

2022-08-10 07:28 UTC, luca020400 commented on app/src/main/java/org/lineageos/selfie/ImageProxyExt.kt
> +        val buffer = plane.buffer
Iirc ByteBuffer has a .array() function call that returns what you want

2022-08-10 15:23 UTC, luca020400 approved these changes

2022-08-10 16:31 UTC, luca020400 requested changes

2022-08-10 16:31 UTC, luca020400 commented on app/src/main/java/org/lineageos/selfie/ImageProxyExt.kt
> +            bytes, width, height, 0, 0, width, height, true
if rotated these are now inverted

2022-08-10 21:17 UTC, merged